name: Unit Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
        
    - name: Create secret
      run: echo '${{ secrets.cookies }}' > /home/runner/work/Action/Action/cookies.json && cat /home/runner/work/Action/Action/cookies.json
      
    - name: Run python
      run: python3 main.py
    
    - name: Run codacy-coverage-reporter
      uses: mrfyda/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
